# Workflow Test
# separate building dependencies : poetry install, project dependencies
# separate static test of code: linter, formatter, security
# separate unit tests

name: Python application Lab01 task4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      run: |
        poetry install --no-root

  lint:
    runs-on: ubuntu-lates
    needs: build
    steps:
      - name: print txt1
        run: ls

  formatter:
    runs-on: ubuntu-lates
    needs: build
    steps:
      - name: print txt2
        run: ls

  security:
    runs-on: ubuntu-lates
    needs: build
    steps:
      - name: print txt3
        run: ls

  unittests:
    runs-on: ubuntu-lates
    needs: [lint, formatter, security]
    steps:
      - name: list files
        run: ls
