# Workflow Test
# separate building dependencies : poetry install, project dependencies
# separate static test of code: linter, formatter, security
# separate unit tests

# Dummy code

name: Python application Lab01 task4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true      
    - name: Install dependencies
      run: |
        poetry install --no-root
  
  # poetry run task lint    
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true      
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: lint run
      run: echo Hello lint 

  # poetry run task formatter
  formatter:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: formatter run
        run: echo Hello formatter

  # poetry run task security
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: security run
        run: echo Hello security

 # poetry run task test
  unittests:
    runs-on: ubuntu-latest
    needs: [lint, formatter, security]
    steps:
      - name: task test run
        run: echo test 
