# Workflow Test
# separate building dependencies : poetry install, project dependencies
# separate static test of code: linter, formatter, security
# separate unit tests

name: Python application Lab01 task4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      run: |
        poetry install --no-root

  display:
    runs-on: ubuntu-lates
    needs: build

    steps:
    - name: print txt
      run: echo Hello display


# job1:
#    runs-on: ubuntu-latest
#    name: lint check  
#    run: poetry run task lint
    
#  job2:
#    runs-on: ubuntu-latest
#    name: formatter
#    steps: 
#    - uses: actions/checkout@v3




 #   - name: Lint with flake8
 #     run: |
 #       poetry run task lint
 #   - name: Test with pytest
 #     run: |
 #       poetry run task test
